spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/curso_java_spring?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    properties:      
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
      
      
